FROM nvidia/opengl:1.0-glvnd-runtime-ubuntu16.04 as nvidia
FROM bionic_melodic_gaz9_robomaker_starting
LABEL maintainer="lejan"

# Installing OpenGL for nvidia-docker2
# https://stackoverflow.com/a/53823600
COPY --from=nvidia /usr/local /usr/local
COPY --from=nvidia /etc/ld.so.conf.d/glvnd.conf /etc/ld.so.conf.d/glvnd.conf

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all

USER root
RUN apt-get update

USER ${user}
